version: '3'
services:
  test-web:
    container_name: test-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      TZ: Asia/Seoul
      TEST_DB_HOST: 'test-db.cxvqxk97tccw.ap-northeast-2.rds.amazonaws.com'
      TEST_DB_DRIVER: 'com.mysql.cj.jdbc.Driver'
      TEST_DB_DATABASE: 'railway'
      TEST_DB_PORT: '6830'
      TEST_DB_USERNAME: 'root'
      TEST_DB_PASSWORD: 'IKtmJ7qw7lpIruzDSwO4'
      TEST_WEB_PROFILE: prod
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - network

  test-db:
    container_name: test-db
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 40s
      retries: 3
    networks:
      - network

networks:
  network: